language: node_js
node_js:
- '0.10'
install:
- npm install -g bower
- npm install
- bower install
script:
- npm test
after_script:
- cat ./tests/coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
